version: '3.7'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./iheb-front:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
